### PR TITLE
Added Help function

### PR DESCRIPTION
**Pull request by barthr**
Help function implemented,

Not very happy about it at the moment. It was a quick solution.

Next:
 - Will format the arguments in JSON file 
 - Some pretty printing

### CODE REVIEW

**Comment by CuriousCain** [comment]
Doesn't look too bad so far, there are some merge conflicts though that need resolving before we can merge the PR.
Can you reconcile these with the updated project changes please?

**Comment by justjoeyuk** [comment]
We're currently looking into a way to decide which command we're going to execute and how to do that effectively. We don't want an "if arg[1] == init {} else if arg[1] == help {} etc". This looks good so far, but as mentioned by @CuriousCain there are some changes that have been made to master.

If you could solve these conflicts and update your branch, we'll look into getting it merged!

Cheers

**Comment by barthr** [comment]
Yes, will do it after dinner. I tought of that problem aswell, because the code will become messy than. Thinking of a solution (probably flags or something) This is my first time contributing to open source. If you have any tips, I would love to hear them

**Comment by justjoeyuk** [comment]
@barthr for now, we're going with a convention of "executeHelp( args []interface{} )" method style. Is that right with you guys @EwanValentine @CuriousCain

**Comment by barthr** [comment]
Ok, I will implement it, probably tomorrow!

**Comment by justjoeyuk** [comment]
@barthr How's it coming along?

**Comment by justjoeyuk** [comment]
@barthr This will be un-assigned at 19:00 this evening if we don't hear back from you. This is to ensure that we are able to complete issues quickly and effectively. Thanks!

**Comment by barthr** [comment]
Yes, i'm only wondering in how I should make it with executeHelp(args...interface) I tought using a switch on os.Args would Be clean aswell

**Comment by CuriousCain** [comment]
@barthr The subcommands system has been updated in master. If you take a look at that, the command flow should be a little more evident

**Comment by barthr** [comment]
Oke i've updated my fork now to the latest and will change my code

**Comment by barthr** [comment]
it's done now! I'm not sure if there any conflicts? my branch is up to date

**Comment by CuriousCain** [comment]
Nice work! I'll merge this

**Pull request merged**
