### PR TITLE
Basic Implementation of Init

### PR DESCRIPTION
**Pull request by justjoeyuk**
Needs improvements. However, it should do for a basic version.

### CODE REVIEW

**Comment by justjoeyuk** [comment]
@EwanValentine @CuriousCain Ready for review :+1:

**Comment by CuriousCain** [comment]
Looks good, not sure what's happened with this though 9aa523a4ba8f148e071350989d36c31a71e92a35

**Comment by justjoeyuk** [comment]
@CuriousCain That'll be `go lint` doing something :P

**Comment by CuriousCain** [comment]
If we can get the formatting fixed, it looks good to merge

**Comment by justjoeyuk** [comment]
Gonna confirm that it's not go lint causing it. If it's not, I'll fix it up.

**Comment by justjoeyuk** [comment]
@CuriousCain it's golint,govet,gofmt doing their thing.

**Comment by CuriousCain** [comment]
Gotcha

**Pull request merged**
